### ISSUE TITLE
`__NEXT_ON_PAGES__KV_SUSPENSE_CACHE` を設定する

### ISSUE THREAD

**Issue by naporin0624** [napolab/v2.0.0_www.napochaan.com#131]
```toml
[[kv_namespaces]]
binding = "__NEXT_ON_PAGES__KV_SUSPENSE_CACHE"
```
